---
- name: Remédiation CIS Global - Correction des écarts de configuration
  hosts: all
  become: yes
  tasks:

    - name: "Appliquer Section 1 - Setup"
      include_tasks: ../tasks/harden_01_setup.yml

    - name: "Appliquer Section 2 - Services"
      include_tasks: ../tasks/harden_02_services.yml

    - name: "Appliquer Section 3 - Réseau"
      include_tasks: ../tasks/harden_03_network.yml

    - name: "Appliquer Section 4 - Logging"
      include_tasks: ../tasks/harden_04_logging.yml

    - name: "Appliquer Section 5 - Accès"
      include_tasks: ../tasks/harden_05_access.yml

  handlers:
    - name: Redémarrer SSH
      service:
        name: ssh
        state: restarted
    - name: Redémarrer Journald
      service:
        name: systemd-journald
        state: restarted
