[servers]
localhost ansible_connection=local ansible_become_pass='emsi'
ubuntu ansible_host=192.168.31.141 ansible_user=user ansible_password='emsi' ansible_become=yes ansible_become_method=sudo ansible_become_password='emsi'
samadsv ansible_host=192.168.31.150 ansible_user=samad ansible_password='samad' ansible_become=yes ansible_become_method=sudo ansible_become_password='samad'
samad ansible_host=192.168.31.150 ansible_user=samad ansible_password='samad' ansible_become=yes ansible_become_method=sudo ansible_become_password='samad'
kali ansible_host=192.168.1.32 ansible_user=kali ansible_password='kali' ansible_become=yes ansible_become_method=sudo ansible_become_password='kali'
